//! Form rendering and interaction engine.

use crossterm::event::{KeyCode, KeyEvent, KeyModifiers};
use ratatui::buffer::Buffer;
use ratatui::layout::{Constraint, Layout, Rect};
use ratatui::text::{Line, Span};
use ratatui::widgets::{Block, Borders, Padding, Widget};

use crate::field_base::BasicField;
use crate::navigation::FocusManager;
use crate::style::FormStyle;
use crate::validation::ValidationError;

/// Result of form submission.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FormResult {
    /// Form was submitted successfully.
    Submitted,
    /// Form was cancelled.
    Cancelled,
    /// Form is still active.
    Active,
}

/// Trait implemented by autogenerated (or custom) form fields containers.
pub trait FormFields {
    /// Returns mutable references to all form fields in tab/display order.
    fn fields_mut(&mut self) -> Vec<&mut dyn BasicField>;

    /// Returns immutable references to all form fields in tab/display order.
    fn fields(&self) -> Vec<&dyn BasicField>;
}

/// A form holding a strongly-typed fields container `F`.
///
/// Fields are stored as named fields inside `F`, which allows direct
/// strongly-typed access via `form.fields.<field_name>`.
pub struct Form<F: FormFields> {
    /// The strongly-typed fields container.
    pub fields: F,
    title: String,
    focus_manager: FocusManager,
    last_focused: Option<usize>,
    style: FormStyle,
    result: FormResult,
    validation_errors: Vec<ValidationError>,
}

impl<F: FormFields> Form<F> {
    /// Creates a new typed form with the given title and fields container.
    pub fn new(title: impl Into<String>, fields: F) -> Self {
        let field_count = fields.fields().len();
        Self {
            fields,
            title: title.into(),
            focus_manager: FocusManager::new(field_count),
            last_focused: None,
            style: FormStyle::default(),
            result: FormResult::Active,
            validation_errors: Vec::new(),
        }
    }

    /// Sets the form style.
    pub fn with_style(mut self, style: FormStyle) -> Self {
        self.style = style;
        self
    }

    /// Returns the raw string value of the field at `index`, if any.
    pub fn value_str(&self, index: usize) -> Option<String> {
        self.fields.fields().get(index).map(|field| field.value_str())
    }

    /// Returns the boolean value of the field at `index`, if it is one.
    pub fn value_bool(&self, index: usize) -> Option<bool> {
        self.fields.fields().get(index).and_then(|field| field.value_bool())
    }

    /// Returns the current form result.
    pub fn result(&self) -> &FormResult {
        &self.result
    }

    /// Returns whether the form is still active.
    pub fn is_active(&self) -> bool {
        self.result == FormResult::Active
    }

    /// Returns validation errors from the last submit attempt.
    pub fn validation_errors(&self) -> &[ValidationError] {
        &self.validation_errors
    }

    /// Handles keyboard input.
    pub fn handle_input(&mut self, event: KeyEvent) {
        // Handle global keys
        match event.code {
            KeyCode::Esc => {
                self.result = FormResult::Cancelled;
                return;
            }
            KeyCode::Tab => {
                if event.modifiers.contains(KeyModifiers::SHIFT) {
                    self.focus_manager.focus_previous();
                } else {
                    self.focus_manager.focus_next();
                }
                self.sync_focus();
                return;
            }
            KeyCode::Enter if self.focus_manager.is_submit_focused() => {
                self.try_submit();
                return;
            }
            KeyCode::Down => {
                if !self.delegate_to_focused_field(&event) {
                    self.focus_manager.focus_next();
                }
                self.sync_focus();
                return;
            }
            KeyCode::Up => {
                if !self.delegate_to_focused_field(&event) {
                    self.focus_manager.focus_previous();
                }
                self.sync_focus();
                return;
            }
            _ => {}
        }

        self.delegate_to_focused_field(&event);
    }

    fn sync_focus(&mut self) {
        let current = if self.focus_manager.is_submit_focused() {
            None
        } else {
            Some(self.focus_manager.current_index())
        };
        if current == self.last_focused {
            return;
        }
        let mut fields = self.fields.fields_mut();
        if let Some(old) = self.last_focused {
            if let Some(field) = fields.get_mut(old) {
                field.on_blur();
            }
        }
        if let Some(new) = current {
            if let Some(field) = fields.get_mut(new) {
                field.on_focus();
            }
        }
        self.last_focused = current;
    }

    fn delegate_to_focused_field(&mut self, event: &KeyEvent) -> bool {
        if self.focus_manager.is_submit_focused() {
            return false;
        }
        self.sync_focus();

        let index = self.focus_manager.current_index();
        let mut fields = self.fields.fields_mut();
        if let Some(field) = fields.get_mut(index) {
            field.handle_input(event)
        } else {
            false
        }
    }

    fn try_submit(&mut self) {
        self.validation_errors.clear();

        let fields = self.fields.fields();
        for (index, field) in fields.iter().enumerate() {
            if let Err(messages) = field.validate() {
                self.validation_errors
                    .extend(messages.into_iter().map(|message| ValidationError {
                        field_index: index,
                        message,
                    }));
            }
        }

        if self.validation_errors.is_empty() {
            self.result = FormResult::Submitted;
        } else {
            if let Some(error) = self.validation_errors.first() {
                self.focus_manager.focus_field(error.field_index);
            }
            self.sync_focus();
        }
    }

    /// Renders the form to a buffer.
    pub fn render(&self, area: Rect, buf: &mut Buffer) {
        let border_style = if self.focus_manager.is_submit_focused() {
            self.style.border
        } else {
            self.style.border_focused
        };

        let block = Block::default()
            .borders(Borders::ALL)
            .border_style(border_style)
            .padding(Padding::horizontal(1))
            .title(Span::styled(&self.title, self.style.title));

        let inner_area = block.inner(area);
        block.render(area, buf);

        if inner_area.height < 2 || inner_area.width < 10 {
            return;
        }

        let fields = self.fields.fields();
        let field_count = fields.len();
        let mut constraints = Vec::with_capacity(field_count + 2);

        for field in &fields {
            constraints.push(Constraint::Length(field.height()));
        }
        constraints.push(Constraint::Length(1)); // Spacer
        constraints.push(Constraint::Length(1)); // Submit button
        constraints.push(Constraint::Min(0)); // Remaining space

        let layout = Layout::vertical(constraints).split(inner_area);

        for (i, field) in fields.iter().enumerate() {
            let is_focused =
                !self.focus_manager.is_submit_focused() && i == self.focus_manager.current_index();
            field.render(layout[i], buf, is_focused, &self.style);
        }

        let submit_idx = field_count + 1;
        if submit_idx < layout.len() {
            self.render_submit_button(layout[submit_idx], buf);
        }

        if !self.validation_errors.is_empty() {
            let error_count = self.validation_errors.len();
            let error_msg = if error_count == 1 {
                "1 validation error".to_string()
            } else {
                format!("{} validation errors", error_count)
            };

            let error_area = Rect {
                x: inner_area.x,
                y: inner_area.y + inner_area.height.saturating_sub(1),
                width: inner_area.width,
                height: 1,
            };

            let error_line = Line::from(Span::styled(error_msg, self.style.error));
            error_line.render(error_area, buf);
        }
    }

    fn render_submit_button(&self, area: Rect, buf: &mut Buffer) {
        let is_focused = self.focus_manager.is_submit_focused();
        let style = if is_focused {
            self.style.button_focused
        } else {
            self.style.button
        };

        let text = if is_focused {
            "[ Submit ]"
        } else {
            "  Submit  "
        };

        let button_width = text.len() as u16;
        let x = area.x + (area.width.saturating_sub(button_width)) / 2;

        for (i, c) in text.chars().enumerate() {
            if x + (i as u16) < area.x + area.width {
                buf[(x + i as u16, area.y)].set_char(c);
                buf[(x + i as u16, area.y)].set_style(style);
            }
        }
    }
}
